=== Taximan/JMaNGOS/conf/packetData/packets.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
 Copyright (C) 2012 JMaNGOS <http://jmangos.org/>                                        
                                                                                         
 This program is free software; you can redistribute it and/or modify it                 
 under the terms of the GNU General Public License as published by the                   
 Free Software Foundation; either version 2 of the License, or (at your                  
 option) any later version.                                                              
                                                                                         
 This program is distributed in the hope that it will be useful, but WITHOUT             
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or                   
 FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for                
 more details.                                                                           
                                                                                         
 You should have received a copy of the GNU General Public License along                 
 with this program. If not, see <http://www.gnu.org/licenses/>.          
-->
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="opcodes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="opcodelist" minOccurs="1" maxOccurs="unbounded"
					type="opcodelist">
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="opcodelist">
		<xs:sequence>
			<xs:element name="packet" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="id" type="xs:string" use="required" />
					<xs:attribute name="name" type="xs:string"  use="required" />
					<xs:attribute name="state" type="ChannelState"
						default="CONNECTED" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="direction" type="PacketDirection" />
		<xs:attribute name="package" type="xs:string" />
	</xs:complexType>

	<xs:simpleType name="PacketDirection">
		<xs:restriction base="xs:string">
			<xs:enumeration value="UPSTREAM" />
			<xs:enumeration value="DOWNSTREAM" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="ChannelState">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CONNECTED" />
			<xs:enumeration value="AUTHED" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Taximan/JMaNGOS/conf/packetData/rc-packets.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Copyright (C) 2012 JMaNGOS <http://jmangos.org/>                                        
                                                                                         
 This program is free software; you can redistribute it and/or modify it                 
 under the terms of the GNU General Public License as published by the                   
 Free Software Foundation; either version 2 of the License, or (at your                  
 option) any later version.                                                              
                                                                                         
 This program is distributed in the hope that it will be useful, but WITHOUT             
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or                   
 FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for                
 more details.                                                                           
                                                                                         
 You should have received a copy of the GNU General Public License along                 
 with this program. If not, see <http://www.gnu.org/licenses/>.          
-->
<opcodes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../Realm/conf/packetData/packets.xsd">
    <opcodelist direction="DOWNSTREAM"
                package="org.jmangos.realm.network.packet.wow.client.">
        <packet name="CMSG_PING" id="1DC" state="AUTHED"/>
        <packet name="CMSG_AUTH_SESSION" id="1ED"/>
        <packet name="CMSG_READY_FOR_ACCOUNT_DATA_TIMES" id="4FF" state="AUTHED"/>
        <packet name="CMSG_REALM_SPLIT" id="38C" state="AUTHED"/>
        <packet name="CMSG_CHAR_ENUM" id="37" state="AUTHED"/>
        <packet name="CMSG_PLAYER_LOGIN" id="3D" state="AUTHED"/>
        <packet name="CMSG_SET_ACTIVE_VOICE_CHANNEL" id="3D3" state="AUTHED"/>
        <packet name="CMSG_CANCEL_TRADE" id="11C" state="AUTHED"/>
        <packet name="CMSG_WORLD_STATE_UI_TIMER_UPDATE" id="4F6" state="AUTHED"/>
        <packet name="CMSG_PLAYED_TIME" id="1CC" state="AUTHED"/>
        <packet name="CMSG_NAME_QUERY" id="50" state="AUTHED"/>
        <packet name="CMSG_SET_ACTIONBAR_TOGGLES" id="2BF" state="AUTHED"/>
        <packet name="CMSG_QUERY_TIME" id="1CE" state="AUTHED"/>
        <packet name="CMSG_QUERY_NEXT_MAIL_TIME" id="284" state="AUTHED"/>
        <packet name="CMSG_LFG_GET_STATUS" id="296" state="AUTHED"/>
        <packet name="CMSG_VOICE_SESSION_ENABLE" id="3AF" state="AUTHED"/>
        <packet name="CMSG_ZONEUPDATE" id="1F4" state="AUTHED"></packet>
        <packet name="CMSG_ITEM_QUERY_SINGLE" id="56" state="AUTHED"/>
        <packet name="CMSG_TUTORIAL_FLAG" id="FE" state="AUTHED"/>
        <packet name="CMSG_SET_ACTIVE_MOVER" id="26A" state="AUTHED"/>
        <packet name="CMSG_SWAP_INV_ITEM" id="10D" state="AUTHED"/>
        <packet name="CMSG_CALENDAR_GET_NUM_PENDING" id="447" state="AUTHED"/>
        <packet name="CMSG_JOIN_CHANNEL" id="097" state="AUTHED"/>
        <packet name="CMSG_GMTICKET_GETTICKET" id="211" state="AUTHED"/>
        <packet name="CMSG_UPDATE_ACCOUNT_DATA" id="20B" state="AUTHED"/>
        <packet name="CMSG_SET_SELECTION" id="13D" state="AUTHED"/>

        <packet name="MSG_MOVE_FALL_LAND" id="C9" state="AUTHED"/>
        <packet name="MSG_MOVE_HEARTBEAT" id="EE" state="AUTHED"/>
        <packet name="MSG_MOVE_JUMP" id="BB" state="AUTHED"/>
        <packet name="MSG_MOVE_SET_FACING" id="0DA" state="AUTHED"/>
        <packet name="MSG_MOVE_SET_PITCH" id="DB" state="AUTHED"/>
        <packet name="MSG_MOVE_SET_RUN_MODE" id="C2" state="AUTHED"/>
        <packet name="MSG_MOVE_SET_WALK_MODE" id="C3" state="AUTHED"/>
        <packet name="MSG_MOVE_START_BACKWARD" id="B6" state="AUTHED"/>
        <packet name="MSG_MOVE_START_FORWARD" id="B5" state="AUTHED"/>
        <packet name="MSG_MOVE_START_PITCH_DOWN" id="C0" state="AUTHED"/>
        <packet name="MSG_MOVE_START_PITCH_UP" id="BF" state="AUTHED"/>
        <packet name="MSG_MOVE_START_STRAFE_LEFT" id="B8" state="AUTHED"/>
        <packet name="MSG_MOVE_START_STRAFE_RIGHT" id="B9" state="AUTHED"/>
        <packet name="MSG_MOVE_START_SWIM" id="CA" state="AUTHED"/>
        <packet name="MSG_MOVE_START_TURN_LEFT" id="BC" state="AUTHED"/>
        <packet name="MSG_MOVE_START_TURN_RIGHT" id="BD" state="AUTHED"/>
        <packet name="MSG_MOVE_STOP" id="B7" state="AUTHED"/>
        <packet name="MSG_MOVE_STOP_PITCH" id="C1" state="AUTHED"/>
        <packet name="MSG_MOVE_STOP_STRAFE" id="BA" state="AUTHED"/>
        <packet name="MSG_MOVE_STOP_SWIM" id="CB" state="AUTHED"/>
        <packet name="MSG_MOVE_STOP_TURN" id="BE" state="AUTHED"/>
        <packet name="CMSG_CREATURE_QUERY" id="60" state="AUTHED"/>

        <!-- paalgyula implemented packets -->
        <packet name="CMSG_CHAR_CREATE" id="36" state="AUTHED"/>
        <packet name="CMSG_REQUEST_RAID_INFO" id="2CD" state="AUTHED"/>
        <packet name="CMSG_STANDSTATECHANGED" id="101" state="AUTHED"/>
        <packet name="CMSG_QUEST_QUERY" id="5C" state="AUTHED"/>
        <packet name="CMSG_MOVE_TIME_SKIPPED" id="2CE" state="AUTHED"/>
        <packet name="CMSG_LOGOUT_REQUEST" id="4B" state="AUTHED"/>
        <!-- gibson implemented packets -->
        <packet name="CMSG_CHAR_CUSTOMIZE" id="473" state="AUTHED"/>
        <packet name="CMSG_CHAR_DELETE" id="038" state="AUTHED"/>
    </opcodelist>
    <opcodelist direction="UPSTREAM"
                package="org.jmangos.realm.network.packet.wow.server.">
        <packet name="SMSG_AUTH_CHALLENGE" id="1EC"/>
        <packet name="SMSG_PONG" id="1DD"/>
        <packet name="SMSG_AUTH_RESPONSE" id="1EE"/>
        <packet name="SMSG_ADDON_INFO" id="2EF"></packet>
        <packet name="SMSG_ACCOUNT_DATA_TIMES" id="209"/>
        <packet name="SMSG_REALM_SPLIT" id="38B"/>
        <packet name="SMSG_CHAR_ENUM" id="3B"/>
        <packet name="SMSG_LOGIN_VERIFY_WORLD" id="236"/>
        <packet name="SMSG_TRADE_STATUS" id="120"/>
        <packet name="SMSG_CLIENTCACHE_VERSION" id="4AB"/>
        <packet name="SMSG_TUTORIAL_FLAGS" id="FD"/>
        <packet name="SMSG_FEATURE_SYSTEM_STATUS" id="3C9"/>
        <packet name="SMSG_MOTD" id="33D"/>
        <packet name="MSG_SET_DUNGEON_DIFFICULTY" id="329"/>
        <packet name="SMSG_SEND_UNLEARN_SPELLS" id="41E"/>
        <packet name="SMSG_INIT_WORLD_STATES" id="2C2"/>
        <packet name="SMSG_BINDPOINTUPDATE" id="155"/>
        <packet name="SMSG_LEARNED_DANCE_MOVES" id="455"/>
        <packet name="SMSG_INSTANCE_DIFFICULTY" id="33B"/>
        <packet name="SMSG_TALENTS_INFO" id="4C0"/>
        <packet name="SMSG_LOGIN_SETTIMESPEED" id="42"/>
        <packet name="SMSG_POWER_UPDATE" id="480"/>
        <packet name="SMSG_COMPRESSED_UPDATE_OBJECT" id="1F6"/>
        <packet name="SMSG_WORLD_STATE_UI_TIMER_UPDATE" id="4F7"/>
        <packet name="SMSG_PLAYED_TIME" id="1CD"/>
        <packet name="SMSG_NAME_QUERY_RESPONSE" id="51"/>
        <packet name="SMSG_QUERY_TIME_RESPONSE" id="1CF"/>
        <packet name="SMSG_ITEM_QUERY_SINGLE_RESPONSE" id="58"/>
        <packet name="SMSG_QUERY_NEXT_MAIL_TIME" id="284"/>
        <packet name="SMSG_ACTION_BUTTONS" id="129"/>
        <packet name="SMSG_INITIAL_SPELLS" id="12A"/>
        <packet name="SMSG_INITIALIZE_FACTIONS" id="122"/>
        <packet name="SMSG_EQUIPMENT_SET_LIST" id="4BC"/>
        <packet name="SMSG_TIME_SYNC_REQ" id="390"/>
        <packet name="SMSG_ALL_ACHIEVEMENT_DATA" id="47D"/>
        <packet name="SMSG_SPELL_GO" id="132"/>
        <packet name="SMSG_CALENDAR_SEND_NUM_PENDING" id="448"/>
        <packet name="SMSG_GMTICKET_GETTICKET" id="212"/>
        <packet name="SMSG_WEATHER" id="2F4"/>
        <packet name="SMSG_CREATURE_QUERY_RESPONSE" id="061"/>
        <!-- paalgyula implemented packets -->
        <packet name="SMSG_CHAR_CREATE" id="3A"/>
        <packet name="SMSG_RAID_INSTANCE_INFO" id="2CC"/>
        <packet name="SMSG_MESSAGE_CHAT" id="96"/>
        <packet name="MSG_MOVE_TIME_SKIPPED" id="319"/>
        <packet name="SMSG_QUEST_QUERY_RESPONSE" id="5D"/>
        <packet name="SMSG_UPDATE_OBJECT" id="A9"/>
        <packet name="SMSG_LOGOUT_COMPLETE" id="4D"/>
        <!-- gibson implemented packets -->
        <packet name="SMSG_CHAR_CUSTOMIZE" id="474"/>
        <packet name="SMSG_TRIGGER_CINEMATIC" id="0FA"/>
        <packet name="SMSG_CHAR_DELETE" id="03C"/>

    </opcodelist>
</opcodes>

=== Taximan/JMaNGOS/conf/packetData/rl-packets.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Copyright (C) 2012 JMaNGOS <http://jmangos.org/>                                        
                                                                                         
 This program is free software; you can redistribute it and/or modify it                 
 under the terms of the GNU General Public License as published by the                   
 Free Software Foundation; either version 2 of the License, or (at your                  
 option) any later version.                                                              
                                                                                         
 This program is distributed in the hope that it will be useful, but WITHOUT             
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or                   
 FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for                
 more details.                                                                           
                                                                                         
 You should have received a copy of the GNU General Public License along                 
 with this program. If not, see <http://www.gnu.org/licenses/>.          
-->
<opcodes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../Realm/conf/packetData/packets.xsd">
	<opcodelist direction="DOWNSTREAM"
		package="org.jmangos.realm.network.packet.auth.client.">
		<packet name="CMD_AUTH_LOGON_CHALLENGE" id="0"></packet>
		<packet name="CMD_AUTH_LOGON_PROOF" id="1" />
		<packet name="CMD_AUTH_ENABLE_CRYPT" id="50" />
		<packet name="CMD_TEST_CRYPT" id="51" />
		<packet name="CMD_SESSION_KEY" id="53" />
	</opcodelist>
	<opcodelist direction="UPSTREAM"
		package="org.jmangos.realm.network.packet.auth.server.">
		<packet name="SMD_AUTH_LOGON_CHALLENGE" id="0"></packet>
		<packet name="SMD_AUTH_LOGON_PROOF" id="1" />
		<packet name="SMD_AUTH_ENABLE_CRYPT" id="50" />
		<packet name="SMD_TEST_CRYPT" id="51" />
		<packet name="SMD_REALM_DATA" id="52" />
		<packet name="SMD_SESSION_KEY" id="53" />
	</opcodelist>
</opcodes>

=== Taximan/JMaNGOS/conf/packetData/lc-packets.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Copyright (C) 2012 JMaNGOS <http://jmangos.org/>                                        
                                                                                         
 This program is free software; you can redistribute it and/or modify it                 
 under the terms of the GNU General Public License as published by the                   
 Free Software Foundation; either version 2 of the License, or (at your                  
 option) any later version.                                                              
                                                                                         
 This program is distributed in the hope that it will be useful, but WITHOUT             
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or                   
 FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for                
 more details.                                                                           
                                                                                         
 You should have received a copy of the GNU General Public License along                 
 with this program. If not, see <http://www.gnu.org/licenses/>.          
-->
<opcodes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="packets.xsd">
	<opcodelist direction="DOWNSTREAM"
		package="org.jmangos.auth.network.packet.wow.client.">
		<packet id="00" name="CMD_AUTH_LOGON_CHALLENGE" state="CONNECTED" />
		<packet id="01" name="CMD_AUTH_LOGON_PROOF" state="CONNECTED" />
		<packet id="02" name="CMD_RECONNECT_CHALLENGE" state="CONNECTED" />
		<packet id="03" name="CMD_RECONNECT_PROOF" state="CONNECTED" />
		<packet id="10" name="CMD_REALM_LIST" state="AUTHED" />
		<packet id="50" name="CMD_AUTH_ENABLE_CRYPT" state="AUTHED" />
		<packet id="51" name="CMD_TEST_CRYPT" state="AUTHED" />
		<packet id="52" name="CMD_REALM_DATA" state="AUTHED" />
		<packet id="53" name="CMD_SESSION_KEY" state="AUTHED" />
	</opcodelist>
	<opcodelist direction="UPSTREAM"
		package="org.jmangos.auth.network.packet.wow.server.">
		<packet id="00" name="SMD_AUTH_LOGON_CHALLENGE" />
		<packet id="01" name="SMD_AUTH_LOGON_PROOF" />
		<packet id="02" name="SMD_RECONNECT_CHALLENGE" />
		<packet id="03" name="SMD_RECONNECT_PROOF" />
		<packet id="10" name="SMD_REALM_LIST" />
		<packet id="50" name="SMD_AUTH_ENABLE_CRYPT" />
		<packet id="53" name="SMD_SESSION_KEY" />
	</opcodelist>
</opcodes>
